#!/usr/bin/env python3
# c in out
# d in out
import sys

mode = sys.argv[1]
input = sys.argv[2]
output = sys.argv[3]

if mode == 'c':
  with open(input, mode='rb') as fi:
    with open(output, mode='wb') as fo:
      last = None
      count = 0
      data = []
      for a in fi.read():
        if a != last or count == 255:
          if last != None:
            data.append(last)
            data.append(count)
          last = a
          count = 1
        else:
          count += 1
      if last != None:
        data.append(last)
        data.append(count)
      fo.write(bytes(data))

elif mode == 'd':
  with open(input, mode='rb') as fi:
    with open(output, mode='wb') as fo:
      data = []
      ichar = False
      charv = None
      for a in fi.read():
        if not ichar:
          charv = a
          ichar = True
          continue
        else:
          for i in range(0, a):
            data.append(charv)
          ichar = False
      fo.write(bytes(data))
